open! Core

(* NOTE: Work In Progress for Mantra library *)

(* NOTE: Syntactically Allowed rules *)
(* INFIX	::=	(CORE ∣ % ∣ <) { OPERATOR } *)
(*  	∣	 # { OPERATOR }+ *)
(* PREFIX	::=	! { OPERATOR } *)
(*  	∣	 (? ∣ ~) { OPERATOR }+ *)
(* OPERATOR	::=	~ ∣ ! ∣ ? ∣ CORE ∣ % ∣ < ∣ : ∣ . *)
(* CORE	::=	$ ∣ & ∣ * ∣ + ∣ - ∣ / ∣ = ∣ > ∣ @ ∣ ^ ∣ | *)

(* NOTE: *)
(* ============AVAILABLE OPERATORS============ *)
(* "$"  - *)
(* "&"  - *)
(* "*"  - *)
(* "+"  - *)
(* "-"  - *)
(* "/"  - *)
(* "="  - *)
(* ">"  - *)
(* "@"  - *)
(* "^"  - *)
(* "|"  - *)
(* "%"  - *)
(* "<"  - *)
(* ============OPERANDS============ *)
(* List -  *)
(* Result - *)
(* Option - *)
(* Map -  *)
(* File - *)
(* String - *)
(* Print - *)
(* Array -  *)
(* ============OPERATIONS============ *)
(* .map *)
(* .fold *)
(* .init *)
(* .bind *)

module Mantra = struct end
